spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: lhj-blog-consumer-feign


server:
  port: 805

eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #客户端注册进eureka服务列表内

feign:
  hystrix:
    enabled: true
	
springcloud:
  configtest: hhh

---
spring:
  profiles: test   #测试环境
  application: 
    name: lhj-blog-consumer-feign

server:
  port: 804

eureka:
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #客户端注册进eureka服务列表内

feign:
  hystrix:
    enabled: true


